name: sliding_number
description: Show number change with a sliding animation.
version: 0.0.1
homepage: https://github.com/dmiedev/sliding_number

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter

flutter:
